version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=vibing
      - DB_USER=postgres
      - DB_PASSWORD=password
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-here
      # S3 Configuration
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKIA3MVITXC2Y3DDZ4EJ
      - AWS_SECRET_ACCESS_KEY=CEb7gz/KbYELtF4nbxzekFh4clSYaYaHZ/OjFdjK
      - S3_BUCKET=vibing-uploads-test
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - vibing-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=vibing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vibing-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vibing"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - vibing-network

volumes:
  postgres_data:

networks:
  vibing-network:
    driver: bridge